version: "3.7"

services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: hormigapg
      POSTGRES_PASSWORD: hormigapg_pass
      POSTGRES_DB: hormigadb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: hormigamq
      RABBITMQ_DEFAULT_PASS: hormigamq_pass
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  postgres_data:
